name: PSP
on:
  pull_request:
  push:
    branches:
      - TDE_REL_17_STABLE
  workflow_dispatch:

jobs:
  build:
    name: PSP
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        compiler: [gcc, clang]
        build_type: [debugoptimized]
        build_script: [make, meson]
    uses: ./.github/workflows/psp-reusable.yml
    with:
        os: ${{ matrix.os }}
        compiler: ${{ matrix.compiler }}
        build_type: ${{ matrix.build_type }}
        build_script: ${{ matrix.build_script }}
    secrets: inherit
